project:
  type: website
  output-dir: _site

metadata-files:
  - reference/_sidebar.yml

format:
  html:
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  package: FileJanitor

  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: File Janitor
      desc: A package of functions for cleaning and organizing files
      contents:
        - flatten
        - index_files
        - replace_pattern
        - standardize_filename